### PR TITLE
Fixes #25998 - pulp3 file creation

### PR DESCRIPTION
**Pull request by jlsherrill**
Left to do:

* [x] Tests
* [x] add foreign keys and indexes
* [x] record walkthrough video of design

Highly Recommend watching: https://www.youtube.com/playlist?list=PL59WSIBtIpv7tbjnsEAWNcdiOKAmjjgqE

### CODE REVIEW

File: app/models/katello/concerns/smart_proxy_extensions.rb [hunk 1]
```diff
@@ -126,6 +126,14 @@ def pulp3_api
         client
       end
 
+      def backend_service_type(repository)
+        if pulp3_support?(repository)
+          Actions::Pulp3::Abstract::BACKEND_SERVICE_TYPE
```
Comment (jturel) [inline app/models/katello/concerns/smart_proxy_extensions.rb]: Need to think on it more but I wonder if this constant should come from somewhere other than an action class. Probably a nitpick either way

Comment (jlsherrill) [reply app/models/katello/concerns/smart_proxy_extensions.rb]: Yeah, i couldn't think of a better place, right now actions are the only ones utilizing it

File: app/services/katello/pulp3/repository.rb [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+          }
+        elsif root.custom?
+          {
+            ssl_client_certificate: root.ssl_client_cert&.content,
+            ssl_client_key: root.ssl_client_key&.content,
+            ssl_ca_certificate: root.ssl_ca_cert&.content
+          }
+        else
+          {}
+        end
```
Comment (jlsherrill) [inline app/services/katello/pulp3/repository.rb]: One thing to ponder, should we pull distribution/remote/publisher out into their own classes?   I'm leaning that way, but might make sense in a future pr rather than this one

**Comment by jlsherrill** [comment]
[test katello]

File: app/models/katello/concerns/smart_proxy_extensions.rb (hunk 1 above)
Comment (parthaa) [reply app/models/katello/concerns/smart_proxy_extensions.rb]: would it be better if this were a method instead of a constant?

**Comment by jlsherrill** [comment]
Pushed a couple of changes:
* Updated distribution creation/update to be async (this introduces new complexity around saving the distribution_href)
* moved initial repository version creation to metadata generation, since it is async

**Comment by sjha4** [comment]
Testing with this, everyhting works well except I noticed that 2 distributors(http and https) were created for every repo in pulp. However the distribution references were not created in katello. I did see an error in the metadata generate task in Actions::Pulp3::Repository::RefreshDistribution which errored with the following and then paused. Upon skip and resume, the Actions::Pulp3::Repository::SaveDistributionReferences task also got skipped.
```

NoMethodError

undefined method `[]' for #<Zest::Distribution:0x00007fa810545500>

---
- "/home/vagrant/katello/app/lib/katello/errors.rb:103:in `from_task'"
- "/home/vagrant/katello/app/lib/actions/pulp3/abstract_async_task.rb:109:in `block
  in external_task='"
- "/home/vagrant/katello/app/lib/actions/pulp3/abstract_async_task.rb:108:in `each'"
- "/home/vagrant/katello/app/lib/actions/pulp3/abstract_async_task.rb:108:in `external_task='"
- "/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.2.2/lib/dynflow/action/polling.rb:83:in
  `initiate_external_action'"

```

**Comment by jlsherrill** [comment]
What version of zest are you using? Can you see if you're on 0.0.4?

**Comment by sjha4** [comment]
> What version of zest are you using? Can you see if you're on 0.0.4?

Ofcourse I was on an older version.. Will test again.. Me--

**Comment by sjha4** [comment]
Works perfectly with 0.0.4! Distributions created and references created.. :tada: :tada:

**Comment by sjha4** [comment]
Couple questions:
1. What are the issues with a single publisher per content type?
2. Should we create remote when creating repo or can we defer that to the first sync?

**Comment by jlsherrill** [comment]
>     What are the issues with a single publisher per content type?

The problem with that is that task locking will prevent multiple publishes on the same publisher from being run, so you'd only be able to publish a single yum repo at a time (for example).

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
@sjha4 and @jjeffers ya'll have played with this a bit now and @parthaa you've looked at it a bit, any objection to merging?  @parthaa want to look a bit more?

**Comment by sjha4** [comment]
This has been working great for me! ACK :+1:

**Comment by jlsherrill** [comment]
@sjha4 mind doing an official review approval?  @parthaa thoughts?

**Comment by parthaa** [comment]
ACK. Code wise looks ok to me.

File: katello.gemspec [hunk 3]
```diff
@@ -42,7 +42,7 @@ Gem::Specification.new do |gem|
   # Pulp
   gem.add_dependency "runcible", ">= 2.11.0", "< 3.0.0"
   gem.add_dependency "anemone"
-
+  gem.add_dependency "zest"
```
Comment (tbrisker) [inline katello.gemspec]: This is missing packaging, now katello builds are failing

Comment (tbrisker) [reply katello.gemspec]: https://github.com/theforeman/foreman-packaging/pull/3592
