### PR TITLE
Fixes #34455 - Migration error related to cdn configuration

### PR DESCRIPTION
**Pull request by parthaa**
#### What are the changes introduced in this pull request?
This fixes a  migration snafu and uses a Fake object.

#### Considerations taken when implementing this change?
Previously when upgrading from 4.1-4.3 you would hit an error along the lines of

```ruby 
== 20211019192121 CreateCdnConfiguration: migrating ===========================
-- create_table(:katello_cdn_configurations)
   -> 0.0053s
-- add_foreign_key(:katello_cdn_configurations, :taxonomies, {:name=>"katello_cdn_configurations_organization_id", :column=>:organization_id})
   -> 0.0017s
-- add_foreign_key(:katello_cdn_configurations, :katello_content_credentials, {:name=>"katello_cdn_configurations_ssl_ca_credential_id", :column=>:ssl_ca_credential_id})
   -> 0.0011s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `type' for #<Katello::CdnConfiguration:0x00000000153c6198>
/opt/theforeman/tfm/root/usr/share/gems/gems/activemodel-6.0.3.7/lib/active_model/attribute_methods.rb:432:in `method_missing'
/opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.3.0.2/app/models/katello/cdn_configuration.rb:40:in `upstream_server?'
/opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.3.0.2/app/models/katello/cdn_configuration.rb:46:in `reset_fields'
```

This code fixes this by using FakeCdnConfiguration

#### What are the testing steps for this pull request?

- Setup a katello 4.1 server (or sat 6.10)
-  Create a few orgs
- Update the packages to 4.3 / 7.0
- Snap shot this vm
- foreman-upgrade should fail with the above error
- revert snapshot and apply the migration changes to `/opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.3.0.2/db/migrate/20211019192121_create_cdn_configuration.katello.rb`
- foreman-upgrade should succeed.

### CODE REVIEW

**Comment by parthaa** [comment]
[test katello]

**Comment by parthaa** [comment]
[test katello]

**Review by chris1984 — APPROVED** [review]
ACK, works good:

Without patch:
```bash
[root@sat-6-10-qa-rhel7 ~]# foreman-installer -l info
2022-02-16 16:57:35 [INFO  ] [configure] /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns:
2022-02-16 16:57:35 [INFO  ] [configure] /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]/returns: undefined local variable or method `type' for #<Katello::CdnConfiguration:0x0000000014a6eaa0>
```

With patch:

```bash
root@sat-6-10-qa-rhel7 ~]# foreman-installer -l info
Upgrade Step 8/8: katello:upgrades:4.4:publish_import_cvvs.   Success!
  * Satellite is running at https://sat-6-10-qa-rhel7.area52.example.com

  * To install an additional Capsule on separate machine continue by running:

      capsule-certs-generate --foreman-proxy-fqdn "$CAPSULE" --certs-tar "/root/$CAPSULE-certs.tar"
  * Capsule is running at https://sat-6-10-qa-rhel7.area52.example.com:9090

  The full log is at /var/log/foreman-installer/satellite.log
Package versions are being locked.
2022-02-16 17:04:23 [INFO  ] [root] Package versions are being locked.
2022-02-16 17:04:26 [INFO  ] [post] All hooks in group post finished

[root@sat-6-10-qa-rhel7 ~]# rpm -qa | grep satellite
satellite-7.0.0-0.5.beta.el7sat.noarch
```bash
