### PR TITLE
Fixes #37178 - use safe navigation for operatingsystem

### PR DESCRIPTION
**Pull request by jeremylenz**
#### What are the changes introduced in this pull request?

Use Ruby safe navigation operator for `operatingsystem`. This fixes a bug introduced in https://github.com/Katello/katello/pull/10881

#### What are the testing steps for this pull request?

Clone a registered rhel8 host
Make sure you can display the host details page without getting a 500

### CODE REVIEW

**Review by chris1984 — COMMENTED** [review]
Code change looks fine and going off what Ewoud said, this looks ok. Going to start testing

**Review by chris1984 — APPROVED** [review]
ACK,

Looks good, before PR:
```ruby
14:02:26 rails.1   | 2024-02-27T14:02:26 [I|app|8bb69bda] Backtrace for 'Action failed' error (ActionView::Template::Error): undefined method `family' for nil:NilClass
14:02:26 rails.1   |  8bb69bda | /home/vagrant/katello/app/views/katello/api/v2/hosts/base.json.rabl:10:in `block in cached_source_4461041918095890411'
```
prbefore


After PR:
No error
prafter

**Comment by jeremylenz** [comment]
rebased

**Comment by ianballou** [comment]
[test katello]
